name: forestguard
description: "AI-powered forest fire prediction application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_generative_ai: ^0.4.6
  flutter_dotenv: ^5.1.0
  flutter_animate: ^4.1.1+1
  http: ^1.1.0
  intl: ^0.20.2
  geolocator: ^13.0.3
  syncfusion_flutter_charts: ^29.1.33


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/logo.jpeg
  uses-material-design: true

